<?php

class PackTableSeeder extends Seeder {

	public function run()
	{
		DB::table('packs')->delete();

		DB::table('packs')->insert(PackTableSeeder::$packs);
	}

	public static $packs = array(
		array('arena' => '1','pack' => '1','card' => '153','pick' => '1'),
		array('arena' => '1','pack' => '1','card' => '142','pick' => '-1'),
		array('arena' => '1','pack' => '1','card' => '94','pick' => '-1'),
		array('arena' => '1','pack' => '2','card' => '283','pick' => '1'),
		array('arena' => '1','pack' => '2','card' => '334','pick' => '-1'),
		array('arena' => '1','pack' => '2','card' => '274','pick' => '-1'),
		array('arena' => '1','pack' => '3','card' => '372','pick' => '-1'),
		array('arena' => '1','pack' => '3','card' => '298','pick' => '1'),
		array('arena' => '1','pack' => '3','card' => '207','pick' => '-1'),
		array('arena' => '1','pack' => '4','card' => '298','pick' => '1'),
		array('arena' => '1','pack' => '4','card' => '249','pick' => '-1'),
		array('arena' => '1','pack' => '4','card' => '387','pick' => '-1'),
		array('arena' => '1','pack' => '5','card' => '438','pick' => '-1'),
		array('arena' => '1','pack' => '5','card' => '274','pick' => '-1'),
		array('arena' => '1','pack' => '5','card' => '174','pick' => '1'),
		array('arena' => '1','pack' => '6','card' => '119','pick' => '-1'),
		array('arena' => '1','pack' => '6','card' => '163','pick' => '1'),
		array('arena' => '1','pack' => '6','card' => '135','pick' => '-1'),
		array('arena' => '1','pack' => '7','card' => '262','pick' => '1'),
		array('arena' => '1','pack' => '7','card' => '435','pick' => '-1'),
		array('arena' => '1','pack' => '7','card' => '436','pick' => '-1'),
		array('arena' => '1','pack' => '8','card' => '315','pick' => '1'),
		array('arena' => '1','pack' => '8','card' => '360','pick' => '-1'),
		array('arena' => '1','pack' => '8','card' => '471','pick' => '-1'),
		array('arena' => '1','pack' => '9','card' => '213','pick' => '-1'),
		array('arena' => '1','pack' => '9','card' => '283','pick' => '-1'),
		array('arena' => '1','pack' => '9','card' => '318','pick' => '1'),
		array('arena' => '1','pack' => '10','card' => '159','pick' => '1'),
		array('arena' => '1','pack' => '10','card' => '96','pick' => '-1'),
		array('arena' => '1','pack' => '10','card' => '137','pick' => '-1'),
		array('arena' => '1','pack' => '11','card' => '32','pick' => '1'),
		array('arena' => '1','pack' => '11','card' => '37','pick' => '-1'),
		array('arena' => '1','pack' => '11','card' => '40','pick' => '-1'),
		array('arena' => '1','pack' => '12','card' => '183','pick' => '1'),
		array('arena' => '1','pack' => '12','card' => '462','pick' => '-1'),
		array('arena' => '1','pack' => '12','card' => '402','pick' => '-1'),
		array('arena' => '1','pack' => '13','card' => '268','pick' => '-1'),
		array('arena' => '1','pack' => '13','card' => '232','pick' => '-1'),
		array('arena' => '1','pack' => '13','card' => '417','pick' => '1'),
		array('arena' => '1','pack' => '14','card' => '283','pick' => '-1'),
		array('arena' => '1','pack' => '14','card' => '255','pick' => '1'),
		array('arena' => '1','pack' => '14','card' => '471','pick' => '-1'),
		array('arena' => '1','pack' => '15','card' => '319','pick' => '-1'),
		array('arena' => '1','pack' => '15','card' => '262','pick' => '1'),
		array('arena' => '1','pack' => '15','card' => '373','pick' => '-1'),
		array('arena' => '1','pack' => '16','card' => '276','pick' => '-1'),
		array('arena' => '1','pack' => '16','card' => '373','pick' => '-1'),
		array('arena' => '1','pack' => '16','card' => '435','pick' => '1'),
		array('arena' => '1','pack' => '17','card' => '341','pick' => '-1'),
		array('arena' => '1','pack' => '17','card' => '268','pick' => '-1'),
		array('arena' => '1','pack' => '17','card' => '463','pick' => '1'),
		array('arena' => '1','pack' => '18','card' => '232','pick' => '-1'),
		array('arena' => '1','pack' => '18','card' => '335','pick' => '-1'),
		array('arena' => '1','pack' => '18','card' => '476','pick' => '1'),
		array('arena' => '1','pack' => '19','card' => '320','pick' => '-1'),
		array('arena' => '1','pack' => '19','card' => '427','pick' => '1'),
		array('arena' => '1','pack' => '19','card' => '451','pick' => '-1'),
		array('arena' => '1','pack' => '20','card' => '118','pick' => '1'),
		array('arena' => '1','pack' => '20','card' => '147','pick' => '-1'),
		array('arena' => '1','pack' => '20','card' => '139','pick' => '-1'),
		array('arena' => '1','pack' => '21','card' => '227','pick' => '-1'),
		array('arena' => '1','pack' => '21','card' => '437','pick' => '-1'),
		array('arena' => '1','pack' => '21','card' => '252','pick' => '1'),
		array('arena' => '1','pack' => '22','card' => '342','pick' => '1'),
		array('arena' => '1','pack' => '22','card' => '451','pick' => '-1'),
		array('arena' => '1','pack' => '22','card' => '253','pick' => '-1'),
		array('arena' => '1','pack' => '23','card' => '451','pick' => '-1'),
		array('arena' => '1','pack' => '23','card' => '283','pick' => '-1'),
		array('arena' => '1','pack' => '23','card' => '315','pick' => '1'),
		array('arena' => '1','pack' => '24','card' => '298','pick' => '1'),
		array('arena' => '1','pack' => '24','card' => '294','pick' => '-1'),
		array('arena' => '1','pack' => '24','card' => '451','pick' => '-1'),
		array('arena' => '1','pack' => '25','card' => '282','pick' => '-1'),
		array('arena' => '1','pack' => '25','card' => '279','pick' => '1'),
		array('arena' => '1','pack' => '25','card' => '425','pick' => '-1'),
		array('arena' => '1','pack' => '26','card' => '178','pick' => '-1'),
		array('arena' => '1','pack' => '26','card' => '232','pick' => '-1'),
		array('arena' => '1','pack' => '26','card' => '319','pick' => '1'),
		array('arena' => '1','pack' => '27','card' => '227','pick' => '-1'),
		array('arena' => '1','pack' => '27','card' => '279','pick' => '1'),
		array('arena' => '1','pack' => '27','card' => '358','pick' => '-1'),
		array('arena' => '1','pack' => '28','card' => '176','pick' => '1'),
		array('arena' => '1','pack' => '28','card' => '283','pick' => '-1'),
		array('arena' => '1','pack' => '28','card' => '396','pick' => '-1'),
		array('arena' => '1','pack' => '29','card' => '232','pick' => '-1'),
		array('arena' => '1','pack' => '29','card' => '213','pick' => '-1'),
		array('arena' => '1','pack' => '29','card' => '183','pick' => '1'),
		array('arena' => '1','pack' => '30','card' => '131','pick' => '-1'),
		array('arena' => '1','pack' => '30','card' => '84','pick' => '-1'),
		array('arena' => '1','pack' => '30','card' => '137','pick' => '1'),
	);

}
